In [1]:
#  Numpy

In [3]:
'!pip install numpy'

'!pip install numpy'


# Numpy array

In [6]:
 my_list=[1,3,5,6]

In [16]:
import numpy as np

arr=np.array(my_list)

In [17]:
arr

array([1, 3, 5, 6])

In [18]:
my_mat=[[1,2,3],[2,3,4],[7,8,0]]

np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 4],
       [7, 8, 0]])

In [24]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [21]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
np.zeros(4)

array([0., 0., 0., 0.])

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.linspace(1,5,15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

# Identity matrix

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



# Random

In [36]:
np.random.rand(6)


array([0.68669372, 0.40345959, 0.84804829, 0.21897144, 0.7012217 ,
       0.82450795])

In [37]:
np.random.rand(3,4)

array([[0.71982955, 0.76856965, 0.23609144, 0.7331548 ],
       [0.75024822, 0.66174738, 0.8881893 , 0.45504452],
       [0.09806028, 0.43317347, 0.98580488, 0.03142601]])

In [27]:
np.random.randn(3,4)

array([[-0.13548953, -0.44955947,  1.32382182, -1.79295808],
       [ 1.08637742, -0.21666546,  2.27154373, -1.91543923],
       [-0.83885204,  0.37399698, -0.27291352,  1.01683354]])

In [38]:
np.random.randint(3,80)

31

In [39]:
ranarr=np.random.randint(22,71,5)

In [40]:
ranarr

array([47, 70, 60, 65, 56])

In [44]:
arr= np.arange(20)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
reshep=arr.reshape(4,5)

In [62]:
reshap

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
ranarr  

array([54, 31, 51, 49, 40, 67, 33, 18, 28, 64])

In [49]:
arr.max()

19

In [50]:
arr.min()

0

In [51]:
arr.argmax()

19

In [52]:
arr.argmin()

0

In [53]:
arr.shape

(20,)

In [63]:
reshap.shape

(4, 5)

In [54]:
reshep.dtype

dtype('int32')

In [65]:
reshap.dtype

dtype('int32')

#  # Numpy indexing and selection

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
arr[7]

7

In [57]:
arr[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
arr[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])


# 2d array or matrix

In [64]:
arr_2d = np.array([[2,3,4],[8,6,0],[1,5,7]])

In [65]:
arr_2d  

array([[2, 3, 4],
       [8, 6, 0],
       [1, 5, 7]])

In [67]:
arr_2d[1][1]

6

In [68]:
arr_2d[1]

array([8, 6, 0])

In [69]:
arr_2d[2][1]

5

In [71]:
# single coma notation

arr_2d[2,1]

5

In [91]:
arr_2d[:,1:2]

array([[3],
       [6],
       [5]])

In [79]:
arr_2d[1:,:2]

array([[8, 6],
       [1, 5]])

In [85]:
Arr= np.arange(1,11) 

In [86]:
Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
B_arr = Arr <= 4

In [91]:
B_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [92]:
Arr[B_arr]

array([1, 2, 3, 4])

In [93]:
Arr[Arr >5]

array([ 6,  7,  8,  9, 10])

In [95]:
Arr[Arr < 6]

array([1, 2, 3, 4, 5])

In [82]:
new_arr = np.arange(50).reshape(5,10)

In [83]:
new_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
new_arr[2:,5:8]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [85]:
new_arr[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
new_arr[:,5:6]

array([[ 5],
       [15],
       [25],
       [35],
       [45]])

# Numpy operation

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [93]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [94]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [95]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [96]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190])

In [97]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31])

In [98]:
arr / arr

C:\Users\hi\AppData\Local\Temp\ipykernel_14504\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
1 / arr

C:\Users\hi\AppData\Local\Temp\ipykernel_14504\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [100]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
        1410065408,  1843829075,  -251658240, -1692154371, -1282129920,
        1500973039,           0,  1681328401,   457441280,  -306639989])

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [120]:
np.max(arr)

19

In [121]:
np.min(arr)

0

In [122]:
arr.max()

19

In [123]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [125]:
np.sin(90)

0.8939966636005579

In [126]:
np.log(arr)

C:\Users\hi\AppData\Local\Temp\ipykernel_16824\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

# Exercise 

In [127]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
  np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [132]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [133]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [134]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [135]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
np.random.rand(1)

array([0.2608819])

In [147]:
np.random.randn(25)

array([ 2.99599722,  0.53628042, -0.6296851 ,  0.6680891 , -0.86649855,
        0.81264081, -0.24526184,  0.15808881, -0.1773307 ,  0.53921971,
        1.33222509,  0.04604027,  0.11717667,  0.07924841, -1.85720605,
       -1.23223087, -0.58655623, -0.64530326, -0.17165558, -0.32431669,
       -0.0422071 , -2.85584352, -0.26506053,  1.52688326, -0.16382107])

In [156]:
np.arange(1,101).reshape(10,10) /100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [158]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [159]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [164]:
mat= np.arange(1,26).reshape(5,5)

In [165]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [166]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [167]:
mat[3,4]

20

In [171]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [176]:
mat[4]

array([21, 22, 23, 24, 25])

In [177]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [178]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [179]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [180]:
np.sum(mat)

325

In [181]:
mat.sum()

325

In [182]:
np.std(mat)    # standard deviation

7.211102550927978

In [183]:
mat.std()

7.211102550927978

In [185]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])